### ISSUE TITLE
Timelapse folders aren't discovered by the TimeLapseModel

### ISSUE THREAD

**Issue by llewelld** [Karry/harbour-timelapse-tools#2]
Directories containing time lapse images are stored at `~/Pictures/.timelapse/<dd>/<MM>/<yyyy hh:mm>` but as far as I can tell the model only checks for directories of the form `~/Pictures/.timelapse/<dir>`, independent of whether they contain images or not.

Consequently it picks up only empty directories for which the Assembly step fails.

**Comment by llewelld** [comment]
PR #3 is an attempt to fix this. It searches recursively through the subdirectories and only registers those containing images with .jpg or .jpeg extensions.

**Comment by Karry** [comment]
Ups. It seems that using locale specific date-time format for timelapse name was not the greatest idea ever. Timelapse name should not contains slash at the first place. 

Thank you for reporting this issue! I will look on your proposal during weekend.

**Comment by llewelld** [comment]
I hadn't realised that the extra directory separators in the name were unintentional, but now you mention it it makes perfect sense. I've updated the PR to use a time format without these forward slashes, which I'm guessing is closer to what you want.

**Comment by Karry** [comment]
Thank you for report. It will be solved by https://github.com/Karry/harbour-timelapse-tools/pull/7 . I decided to rework the list of timelapses a bit.
