### ISSUE TITLE
Keyboard covers entry fields on Xperia 10 * devices

### ISSUE THREAD

**Issue by llewelld** [Karry/harbour-timelapse-tools#5]
On the 21:9 ratio screens of the Xperia 10 etc. devices, when the caret is in some input fields (e.g. the "Image count" field), the pane on the left hand side doesn't scroll up enough, and so the field is covered by the keyboard, making it hard to enter values.

**Comment by llewelld** [comment]
PR #6 is an attempt to address this. It updates the flickable height as the tab changes.

**Comment by Karry** [comment]
Thank you!
